"""
Agri Gram AI - Extra Module 2
PDF report generation, SMS (Fast2SMS / Twilio) notifications, analytics summary.
Author: Abinaya K
"""

import os
import io
from datetime import datetime


# ============================================================
#  FAST2SMS (India) - send real SMS easily
# ============================================================
def send_sms_fast2sms(to_number, message):
    """
    Send an SMS via Fast2SMS (India).
    Set environment variable FAST2SMS_KEY with your API key.
    Get a free key at https://www.fast2sms.com (Dev API -> API Key).
    `to_number` should be a 10-digit Indian number (no +91).
    Requires: requests
    """
    api_key = os.environ.get("FAST2SMS_KEY", "")
    # Keep only the last 10 digits (Fast2SMS wants plain 10-digit numbers)
    digits = "".join(ch for ch in to_number if ch.isdigit())[-10:]

    if not api_key:
        return {
            "sent": False,
            "reason": "Fast2SMS not configured. Set FAST2SMS_KEY environment "
                      "variable (get a free key at fast2sms.com).",
            "demo_message": message,
            "to": digits,
        }

    try:
        import requests
        url = "https://www.fast2sms.com/dev/bulkV2"
        payload = {
            "route": "q",              # quick transactional route
            "message": message,
            "language": "english",
            "numbers": digits,
        }
        headers = {"authorization": api_key}
        r = requests.post(url, data=payload, headers=headers, timeout=10)
        data = r.json()
        if data.get("return") is True:
            return {"sent": True, "provider": "Fast2SMS",
                    "request_id": data.get("request_id"), "to": digits}
        return {"sent": False, "reason": str(data), "to": digits}
    except Exception as e:
        return {"sent": False, "reason": str(e), "to": digits}


# ============================================================
#  1. PDF REPORT GENERATION
# ============================================================
def generate_pdf_report(data):
    """
    Build a farmer report PDF in memory and return the bytes.
    `data` is a dict with optional keys: farmer_name, location, crop,
    soil, water, weather_summary, profit, yield_kg, notes.
    Requires: reportlab
    """
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm
    from reportlab.lib import colors
    from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer,
                                    Table, TableStyle)
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4,
                            topMargin=20*mm, bottomMargin=20*mm)
    styles = getSampleStyleSheet()
    green = colors.HexColor("#2e7d32")

    title_style = ParagraphStyle("t", parent=styles["Title"],
                                 textColor=green, fontSize=22)
    h2 = ParagraphStyle("h2", parent=styles["Heading2"], textColor=green)
    normal = styles["Normal"]

    elems = []
    elems.append(Paragraph("🌾 Agri Gram AI - Farm Report", title_style))
    elems.append(Paragraph(
        f"Generated: {datetime.now().strftime('%d %B %Y, %I:%M %p')}", normal))
    elems.append(Spacer(1, 8*mm))

    # Farmer / field info
    info_rows = [
        ["Farmer Name", data.get("farmer_name", "-")],
        ["Location", data.get("location", "-")],
        ["Selected Crop", data.get("crop", "-")],
        ["Soil Type", data.get("soil", "-")],
    ]
    t = Table(info_rows, colWidths=[60*mm, 100*mm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#e8f5e9")),
        ("TEXTCOLOR", (0, 0), (0, -1), green),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))
    elems.append(t)
    elems.append(Spacer(1, 8*mm))

    # Recommendations section
    elems.append(Paragraph("Recommendations", h2))
    recs = [
        ["Water Requirement", data.get("water", "-")],
        ["Weather Summary", data.get("weather_summary", "-")],
        ["Expected Yield", data.get("yield_kg", "-")],
        ["Estimated Profit", data.get("profit", "-")],
    ]
    t2 = Table(recs, colWidths=[60*mm, 100*mm])
    t2.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))
    elems.append(t2)
    elems.append(Spacer(1, 8*mm))

    if data.get("notes"):
        elems.append(Paragraph("Notes", h2))
        elems.append(Paragraph(data["notes"], normal))

    elems.append(Spacer(1, 12*mm))
    elems.append(Paragraph(
        "<i>Report generated by Agri Gram AI - Smart Farming Assistant "
        "by Abinaya K</i>", normal))

    doc.build(elems)
    buffer.seek(0)
    return buffer


# ============================================================
#  2. SMS / TWILIO NOTIFICATIONS
# ============================================================
def send_sms(to_number, message):
    """
    Send an SMS via Twilio.
    Set these environment variables (or replace below):
      TWILIO_SID, TWILIO_TOKEN, TWILIO_FROM
    Requires: twilio
    Returns a status dict (does not crash if not configured).
    """
    sid = os.environ.get("TWILIO_SID", "")
    token = os.environ.get("TWILIO_TOKEN", "")
    from_num = os.environ.get("TWILIO_FROM", "")

    if not (sid and token and from_num):
        return {
            "sent": False,
            "reason": "Twilio not configured. Set TWILIO_SID, TWILIO_TOKEN, "
                      "TWILIO_FROM environment variables.",
            "demo_message": message,
            "to": to_number
        }

    try:
        from twilio.rest import Client
        client = Client(sid, token)
        msg = client.messages.create(body=message, from_=from_num, to=to_number)
        return {"sent": True, "sid": msg.sid, "to": to_number}
    except Exception as e:
        return {"sent": False, "reason": str(e), "to": to_number}


def build_farm_alert(crop, weather_advice):
    """Compose a short SMS alert message for a farmer."""
    return (f"🌾 Agri Gram AI Alert: For your {crop} crop - {weather_advice} "
            f"Stay safe & farm smart!")


# ============================================================
#  3. ANALYTICS SUMMARY (extra stats for dashboard)
# ============================================================
def analytics_summary():
    """Return summary stats + water comparison for the dashboard."""
    from agri_features import CROP_ECONOMICS

    water_map = {
        "Rice": 1200, "Wheat": 450, "Cotton": 700, "Sugarcane": 1800,
        "Groundnut": 500, "Maize": 600, "Millets": 350, "Pulses": 400,
        "Vegetables": 550, "Coconut": 900,
    }
    crops = list(CROP_ECONOMICS.keys())

    profit_list, water_list = [], []
    for c in crops:
        info = CROP_ECONOMICS[c]
        profit = info["yield"] * info["price"] - info["cost"]
        profit_list.append({"crop": c, "profit": round(profit)})
        water_list.append({"crop": c, "water_mm": water_map.get(c, 500)})

    profit_list.sort(key=lambda x: x["profit"], reverse=True)
    water_list.sort(key=lambda x: x["water_mm"])

    best = profit_list[0]
    least_water = water_list[0]
    return {
        "total_crops": len(crops),
        "most_profitable": best["crop"],
        "most_profitable_value": best["profit"],
        "least_water_crop": least_water["crop"],
        "least_water_value": least_water["water_mm"],
        "profit_comparison": profit_list,
        "water_comparison": water_list,
    }
